
CREATE TABLE `imports` (
  `import-id` varchar(32) NOT NULL DEFAULT '',
  `peer-id` varchar(32) NOT NULL DEFAULT '',
  `uploader-email-id` varchar(32) NOT NULL DEFAULT '',
  `maps-id` varchar(32) NOT NULL DEFAULT '',
  `country-ids` tinytext NOT NULL,
  `ip-id` varchar(32) NOT NULL DEFAULT '',
  `referee` varchar(44) NOT NULL DEFAULT '',
  `subject` varchar(200) NOT NULL DEFAULT '',
  `filename` varchar(200) NOT NULL DEFAULT '',
  `path` varchar(200) NOT NULL DEFAULT '',
  `bytes` int(18) NOT NULL DEFAULT '0',
  `columns` int(8) NOT NULL DEFAULT '0',
  `records` int(12) NOT NULL DEFAULT '0',
  `duplicates` int(12) NOT NULL DEFAULT '0',
  `inactivity` int(12) NOT NULL DEFAULT '0',
  `verified` int(12) NOT NULL DEFAULT '0',
  `maintenances` int(12) NOT NULL DEFAULT '0',
  `expiries` int(12) NOT NULL DEFAULT '0',
  `uploaded` int(12) NOT NULL DEFAULT '0',
  `fields-seperated` varchar(6) NOT NULL DEFAULT ',',
  `fields-strings` varchar(6) NOT NULL DEFAULT '"',
  `fields-escapes` varchar(6) NOT NULL DEFAULT '\\',
  `fields-eol` varchar(6) NOT NULL DEFAULT '\n',
  PRIMARY KEY (`import-id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
