
CREATE TABLE `" . $GLOBALS['APIDB']->prefix('imports_columns') . "` (
  `column-id` int(24) NOT NULL AUTO_INCREMENT,
  `maps-id` varchar(32) NOT NULL DEFAULT '',
  `position` int(12) NOT NULL DEFAULT '0',
  `title` varchar(150) NOT NULL DEFAULT '',
  `field` enum('Category','Title','Full Name','First Name','Middle Name','Last Name','Suffix','Company','Department','Job Title','Instant Messaging One','Instant Messaging Two','Business Street One','Business Street Two','Business Street Three','Business Province','Business City','Business State','Business Country','Business Postcode','Business Longitude','Business Latitude','Business Serial Number Postage','Home Street One','Home Street Two','Home Street Three','Home Province','Home City','Home State','Home Country','Home Postcode','Home Longitude','Home Latitude','Home Serial Number Postage','Other Street One','Other Street Two','Other Street Three','Other Province','Other City','Other State','Other Country','Other Postcode','Other Longitude','Other Latitude','Other Serial Number Postage','Assistant Phone Number','Business Fax Number','Business Phone Number One','Business Phone Number Two','Callback Phone Number','Car Phone Number','Business Switch Phone Number','Home Fax Number','Home Phone Number One','Home Phone Number Two','ISDN Phone Number','Mobile Phone Number','Other Phone Number','Other Fax Number','Pager Phone Number','Primary Phone Number','Radio Phone Number','TTY/TDD Phone Number','Telex','Account','Anniversary','Assistants Name','Billing Information','Birthday','Children','Email One Address','Email One Display Name','Email Two Address','Email Two Display Name','Email Three Address','Email Three Display Name','Gender','Government ID Number','Hobby','Intials','Keywords','Languages','Country','Location Place','Milage','Notes','Office Country','Office Location Place','Registered Business Number','Profession','Refereed By','Spouse','Web Page Primary','Web Page Blog','Web Page Facebook','Web Page Twitter','Web Page Linked-in','Web Page Google+','Web Page Other','Skip (Unknown)') NOT NULL DEFAULT 'Skip (Unknown)' COMMENT 'ENUM(''Title'', ''Full Name'', ''First Name'', ''Middle Name'', ''Suffix'', ''Company'', ''Department'', ''Job Title'', ''Business Street One'', ''Business Street Two'', ''Business Street Three'', ''Business Province'', ''Business City'', ''Business State'', ''Business Country'', ''Business Postcode'', ''Business Longitude'', ''Business Latitude'', ''Business Serial Number Postage'',  ''Home Street One'', ''Home Street Two'', ''Home Street Three'', ''Home Province'', ''Home City'', ''Home State'', ''Home Country'', ''Home Postcode'', ''Home Longitude'', ''Home Latitude'', ''Home Serial Number Postage'',  ''Other Street One'', ''Other Street Two'', ''Other Street Three'', ''Other Province'', ''Other City'', ''Other State'', ''Other Country'', ''Other Postcode'', ''Other Longitude'', ''Other Latitude'', ''Other Serial Number Postage'', ''Assistant Phone Number'', ''Business Fax Number'', ''Business Phone Number One'', ''Business Phone Number Two'', ''Callback Phone Number'', ''Car Phone Number'', ''Business Switch Phone Number'', ''Home Fax Number'', ''Home Phone Number One'', ''Home Phone Number Two'', ''ISDN P',
  `type` enum('String','Integer','Unix Time Stamp','URL','Email','Phone Number','Date','Time','Date/time','Unknown') NOT NULL DEFAULT 'Unknown',
  `data` tinytext,
  PRIMARY KEY (`column-id`)
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8;

