
CREATE TABLE `whois` (
  `whois-id` varchar(32) NOT NULL,
  `typal` enum('realm','ipv4','ipv6') NOT NULL DEFAULT 'realm',
  `state` enum('current','historical') NOT NULL DEFAULT 'current',
  `realm-id` varchar(32) NOT NULL DEFAULT '',
  `ipv4-id` varchar(32) NOT NULL DEFAULT '',
  `ipv6-id` varchar(32) NOT NULL DEFAULT '',
  `history-whois-id` mediumint(20) unsigned NOT NULL DEFAULT '0',
  `registrar-serial` varchar(20) NOT NULL DEFAULT '0',
  `registrar-name-id` mediumint(20) unsigned NOT NULL DEFAULT '0',
  `registrar-address-id` mediumint(20) unsigned NOT NULL DEFAULT '0',
  `registrar-email-id` mediumint(20) unsigned NOT NULL DEFAULT '0',
  `registrar-phone-id` mediumint(20) unsigned NOT NULL DEFAULT '0',
  `registrar-fax-id` mediumint(20) unsigned NOT NULL DEFAULT '0',
  `general-serial` varchar(20) NOT NULL DEFAULT '0',
  `general-name-id` mediumint(20) unsigned NOT NULL DEFAULT '0',
  `general-address-id` mediumint(20) unsigned NOT NULL DEFAULT '0',
  `general-email-id` mediumint(20) unsigned NOT NULL DEFAULT '0',
  `general-phone-id` mediumint(20) unsigned NOT NULL DEFAULT '0',
  `general-fax-id` mediumint(20) unsigned NOT NULL DEFAULT '0',
  `admin-serial` varchar(20) NOT NULL DEFAULT '0',
  `admin-name-id` mediumint(20) unsigned NOT NULL DEFAULT '0',
  `admin-address-id` mediumint(20) unsigned NOT NULL DEFAULT '0',
  `admin-email-id` mediumint(20) unsigned NOT NULL DEFAULT '0',
  `admin-phone-id` mediumint(20) unsigned NOT NULL DEFAULT '0',
  `admin-fax-id` mediumint(20) unsigned NOT NULL DEFAULT '0',
  `technical-serial` varchar(20) NOT NULL DEFAULT '0',
  `technical-name-id` mediumint(20) unsigned NOT NULL DEFAULT '0',
  `technical-address-id` mediumint(20) unsigned NOT NULL DEFAULT '0',
  `technical-email-id` mediumint(20) unsigned NOT NULL DEFAULT '0',
  `technical-phone-id` mediumint(20) unsigned NOT NULL DEFAULT '0',
  `technical-fax-id` mediumint(20) unsigned NOT NULL DEFAULT '0',
  `hits` int(13) unsigned NOT NULL DEFAULT '0',
  `created` int(13) unsigned NOT NULL DEFAULT '0',
  `history` int(13) unsigned NOT NULL DEFAULT '0',
  PRIMARY KEY (`whois-id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
